services:

  homepage:
      image: ghcr.io/gethomepage/homepage:latest
      container_name: homepage
      ports:
        - 3001:3000
      env_file: .env  
      volumes:
        - ./config:/app/config 
      environment:
        - PUID=${PUID}
        - PGID=${PGID}

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./BE:/app
    env_file:
      - BE/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./FE:/app
    env_file:
      - FE/.env
    depends_on:
      - backend

  database:
    image: postgres:16.4
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    env_file:
      - .db.env
    environment:
      DATA_SOURCE_NAME: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@database:5432/$POSTGRES_DB?sslmode=disable
    depends_on:
      - database
    ports:
      - "9187:9187"  

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus

volumes:
  db_data:
  grafana_data: