---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Apps:
    - Lista de Contactos:
        href: http://localhost:3000/
        description: Criar, guarda e remove os teus contactos.
        icon: mdi-contacts-#FF0000

- Tools:
    - Grafana:
        href: https://afonsosgb.grafana.net/a/cloud-home-app
        icon: si-grafana-#F46800

    - Prometheus:
        href: https://prometheus.io/
        icon: si-prometheus-#E6522C

    - Glances:
        href: http://localhost:61208/
        icon: sh-glances.svg